// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATenLQRFVrv-deOMugNiHH1xrNoiRqgjs',
    appId: '1:41725040358:web:bc2b6eaad9f0c4c8e64d27',
    messagingSenderId: '41725040358',
    projectId: 'fluttertest-730c6',
    authDomain: 'fluttertest-730c6.firebaseapp.com',
    storageBucket: 'fluttertest-730c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu_q4Zmod-Hlu57GlW_rA5WLaTjlQ66o0',
    appId: '1:41725040358:android:6de3f4b0ec49ff82e64d27',
    messagingSenderId: '41725040358',
    projectId: 'fluttertest-730c6',
    storageBucket: 'fluttertest-730c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDQAS8BPGmlyON107BQcNoQDY3JOw5U0',
    appId: '1:41725040358:ios:866c50a6351a4d08e64d27',
    messagingSenderId: '41725040358',
    projectId: 'fluttertest-730c6',
    storageBucket: 'fluttertest-730c6.appspot.com',
    iosBundleId: 'com.example.fireproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpDQAS8BPGmlyON107BQcNoQDY3JOw5U0',
    appId: '1:41725040358:ios:13ab738dddec9521e64d27',
    messagingSenderId: '41725040358',
    projectId: 'fluttertest-730c6',
    storageBucket: 'fluttertest-730c6.appspot.com',
    iosBundleId: 'com.example.fireproject.RunnerTests',
  );
}
